spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
    test-connection: true
  application:
    name: email
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-18-235-235-165.compute-1.amazonaws.com:5432/d6buh0t4uhcjqk
    username: ${DBUSER}
    password: ${DBPASS}

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

server:
  port: 8081

eureka:
  instance:
    non-secure-port: 80
    hostname: api-email-jj.herokuapp.com
  client:
    service-url:
      defaultZone: https://secret-anchorage-03030.herokuapp.com/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: api-login by joao4018
  website: https://www.linkedin.com/in/joao4018/
  github: https://github.com/joao4018

ribbon:
  ReadTimeout: 2147483647
  ConnectTimeout: 2147483647
